"""empty message

Revision ID: d6cd0e2114df
Revises: 67f70e573ddc
Create Date: 2025-11-09 17:34:17.555485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd6cd0e2114df'
down_revision: Union[str, Sequence[str], None] = '67f70e573ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'buildings', 'latitude',
        existing_type=sa.VARCHAR(),
        type_=sa.Numeric(precision=14, scale=12),
        existing_nullable=False,
        postgresql_using='latitude::numeric(15,13)'
    )
    op.alter_column(
        'buildings', 'longitude',
        existing_type=sa.VARCHAR(),
        type_=sa.Numeric(precision=15, scale=12),
        postgresql_using='longitude::numeric(15,13)',
        existing_nullable=False)

    op.drop_constraint(op.f('organizations_activities_activity_uuid_fkey'), 'organizations_activities',
                       type_='foreignkey')
    op.create_foreign_key('organizations_activities_activity_uuid_fkey', 'organizations_activities', 'activities',
                          ['activity_uuid'], ['uuid'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'buildings', 'longitude',
        existing_type=sa.Numeric(precision=15, scale=12),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using='longitude::varchar'
    )
    op.alter_column(
        'buildings', 'latitude',
        existing_type=sa.Numeric(precision=14, scale=12),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using='latitude::varchar'
    )

    op.drop_constraint('organizations_activities_activity_uuid_fkey', 'organizations_activities', type_='foreignkey')
    op.create_foreign_key(op.f('organizations_activities_activity_uuid_fkey'), 'organizations_activities', 'activities',
                          ['activity_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###
